package capstonesu25.warehouse.enums;

public enum RequestStatus {
    NOT_STARTED, IN_PROGRESS, EXTENDED ,COUNTED, COUNT_CONFIRMED, WAITING_EXPORT, CONFIRMED, COMPLETED, CANCELLED,READY_TO_STORE,STORED
}
