package capstonesu25.warehouse.annotation.generateId;

import jakarta.persistence.MappedSuperclass;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
@MappedSuperclass
public @interface AutoGeneratedId {
    String parentField();
}
