spring:
  application:
    name: warehouse
    security:
      jwt:
        access_token:
          secret: ${JWT_ACCESS_TOKEN_SECRET}
          expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
        refresh_token:
          secret: ${JWT_REFRESH_TOKEN_SECRET}
          expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  pusher:
    app-id: ${PUSHER_APP_ID}
    key: ${PUSHER_APP_KEY}
    secret: ${PUSHER_APP_SECRET}
    cluster: ${PUSHER_APP_CLUSTER}
  main:
    allow-bean-definition-overriding: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  show-actuator: false
  enable-data-rest: false

cloudinary:
  url: ${CLOUDINARY_URL}

