spring:
  application:
    name: warehouse
    security:
      jwt:
        access_token:
          secret: de2a11b64cb8a10bbfa6ca0a4afb3578cc434cda024b8817b0cf98e38b61b9f3
          expiration: 6000000
        refresh_token:
          secret: 85ec7a7e649be00c51fe797ae418fc06aa5fc0a80f90afa674eac1a8521e0832
          expiration: 604800000
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  pusher:
    app-id: 1986383
    key: 0c02fd43e1874d8d71e4
    secret: 47b1d062f7c1fe2e3b1f
    cluster: ap1
  main:
    allow-bean-definition-overriding: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  show-actuator: false
  enable-data-rest: false

cloudinary:
  url: cloudinary://767784219196157:LsUP8FBcIx6dHW7jP_FnxuxOHUY@dkgopfdx9

