spring:
  application:
    name: warehouse
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  show-actuator: false
  enable-data-rest: false

cloudinary:
  url: ${CLOUDINARY_URL}

