spring:
  application:
    name: warehouse
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 120000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  show-actuator: false
  enable-data-rest: false

cloudinary:
  url: ${CLOUDINARY_URL}

