spring:
  application:
    name: warehouse
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
