name: Build and Deploy to DO App Platform

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push multi-platform image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: doanvinhphu321/warehouse:latest

    - name: Trigger redeploy on DigitalOcean App Platform
      env:
        DO_API_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      run: |
        curl -X POST "https://api.digitalocean.com/v2/apps/77ed28dd-5818-411e-a277-ce04791a50f4/deployments" \
          -H "Authorization: Bearer $DO_API_TOKEN" \
          -H "Content-Type: application/json"